
spring:
  application:
    name: product-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: hibernate
    username: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    properties:
      hibernate:
       format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/